### ISSUE TITLE
SimpleSpec comparison not producing documented results

### ISSUE THREAD

**Issue by soda480** [rbarrois/python-semanticversion#103]
Per your documentation the following should return True:
```
>>> s = SimpleSpec('==0.1.1')
>>> Version('0.1.1-alpha1') in s
False

```

**Comment by rbarrois** [comment]
Hi, and thanks for the report!

Could you point to the place in the docs which says that? The first mention of comparison and pre-release identifier in the docs says that:

> A clause of ==0.1.2 will match version 0.1.2 and any version differing only through its build number (0.1.2+b42 matches);

There have been significant changes in version 2.7, I might have missed some parts of the doc during the migration ;)

**Comment by soda480** [comment]
It is located in the README, here: 
https://github.com/rbarrois/python-semanticversion#requirement-specification

```
>>> s = SimpleSpec('==0.1.1')
>>> Version('0.1.1-alpha1') in s
True
```

**Comment by rbarrois** [comment]
Thanks for the report! I've fixed the README :)
