### ISSUE TITLE
Docs say that named components patch must be both an integer and a tuple of strings

### ISSUE THREAD

**Issue by claremacrae** [rbarrois/python-semanticversion#104]
This text is present in both `README.rst` and `docs/index.rst`:

```rst
In that case, ``major``, ``minor`` and ``patch`` are mandatory, and must be integers.
``prerelease`` and ``patch``, if provided, must be tuples of strings:
```

I think the second `patch` reference must be to some other argument instead...

**Comment by rbarrois** [comment]
Good catch! The second should indeed by ``build``, fixing it now :)

**Comment by claremacrae** [comment]
Wow - that was quick - thanks @rbarrois !
