### ISSUE TITLE
Setup.cfg shows support for EOL Python versions?

### ISSUE THREAD

**Issue by gnattishness** [rbarrois/python-semanticversion#114]
Hi,
In `setup.cfg`, the current package metadata and `python_requires` indicates that the EOL python versions 2.7, 3.4, 3.5 are currently supportedby this package.
Is this intended?

If not, I'm happy to submit a PR updating this.
(I'm just in the process of an unrelated PR and wanting to double check if I should be taking them into account)

Thanks!

**Comment by rbarrois** [comment]
Hi!

They are indeed supported; the cost of supporting those versions is quite low, and that keeps the library compatible with older projects.
If I remember correctly, this library is used by some packaging tools — they especially care about long term backwards compatibility!

Moreover, being focused on semantic versioning, dropping compatibility with Python 2 would require a major version bump 😛

**Comment by gnattishness** [comment]
Many thanks for the clarification!
