### ISSUE TITLE
Is `parse(..., partial=True)` deprecated too?

### ISSUE THREAD

**Issue by guludo** [rbarrois/python-semanticversion#117]
Hi there.

I see that creating a `Version` instance with `partial=True` is deprecated now. Is it okay though to continue using `Version.parse()` with `partial=True`?

Regards,
Gustavo Sousa

**Comment by rbarrois** [comment]
It is indeed as well; the idea is:
- Use `Version.coerce()` to convert arbitrary data into a valid `Version`;
- Use `SimpleSpec()` with wildcards (e.g. `SimpleSpec("==1.*")` for "Anything in the 1.x series"

**Comment by guludo** [comment]
Okay. Thanks for the clarification!
