### ISSUE TITLE
Release Django 4.0 compatible version on PyPi

### ISSUE THREAD

**Issue by squio** [rbarrois/python-semanticversion#125]
Currently the [published version at pypi](https://pypi.org/project/semantic-version/) is still at 2.8.5 from Apr 29, 2020

Can we please have a release with the [Django 4.0 compatibility fixes](https://github.com/rbarrois/python-semanticversion/pull/123)?

**Comment by mgorny** [comment]
Ping.

**Comment by rbarrois** [comment]
Hey! That's finally done, sorry for the delay.

The main documentation file used some Sphinx markup, which is not supported by PyPI for its packages.
