### ISSUE TITLE
Support setuptools-scm

### ISSUE THREAD

**Issue by fubuloubu** [rbarrois/python-semanticversion#126]
When using `setuptools-scm` on a branch in development, the version is something like `x.y.z.dev11+g24645856`. Knowing that this doesn't comply to semantic-version, I don't think it necessarily needs to because it's suppose to represent and "untagged" state that is in development, and not a semantically viable version.

A key thing to note is that `.z` is +1 above the latest tagged version, so it might be appropiate to simply split off the `.dev` portion (unsure if this would be good)

Not sure how best to handle thing, but I think it would be good to have a way to handle this somehow because it currently breaks the version parser which is pretty annoying when you're working with packages that use `setuptools-scm`

**Comment by rbarrois** [comment]
Have you tried working with `Version.coerce()`?

As far as I can tell, it mostly works:
```python
>>> v = Version.coerce("1.2.3.dev11+g24645856")
>>> v
Version("1.2.3+dev11.g24645856")
>>> list(v)
(1, 2, 3, (), ("dev11", "g24645856"))
```

**Comment by fubuloubu** [comment]
> Have you tried working with `Version.coerce()`?
> 
> As far as I can tell, it mostly works:
> 
> ```python
> >>> v = Version.coerce("1.2.3.dev11+g24645856")
> >>> v
> Version("1.2.3+dev11.g24645856")
> >>> list(v)
> (1, 2, 3, (), ("dev11", "g24645856"))
> ```

Great tip! Will give this a shot

**Comment by rbarrois** [comment]
Hey! I'm doing some cleanup here, so I'll close this issue since it looks like your issue was fixed.
However, feel free to reopen it if need be :)
