### ISSUE TITLE
Add topics (keywords) in the About section of the repository page

### ISSUE THREAD

**Issue by pikhovkin** [rbarrois/python-semanticversion#134]
Add topics (keywords) in the **About** section of the repository page

**Comment by rbarrois** [comment]
Without more details on the expected gains, I don't know what to do with this suggestion!

**Comment by pikhovkin** [comment]
![image](https://user-images.githubusercontent.com/630071/175765170-bd2ce88e-faa1-4599-9243-51f6a0a8924f.png)
