### ISSUE TITLE
Comparison with suffixes is just alphabetical

### ISSUE THREAD

**Issue by jquentin-lion** [rbarrois/python-semanticversion#135]
```python
>>> max(Version("1.1.1-rc10"), Version("1.1.1-rc9"))
Version('1.1.1-rc9')
```

It would probably make sense to behave the same as for the major, minor and patch here, for anything that matches "d+" in the suffix.

**Comment by rbarrois** [comment]
Sorry, that is not consistent with the [semver specification](https://semver.org/#spec-item-11):

> Identifiers with letters or hyphens are compared lexically in ASCII sort order.
