### ISSUE TITLE
Constraints not properly evaluated for prerelease versions

### ISSUE THREAD

**Issue by mkjpryor** [rbarrois/python-semanticversion#137]
I am using this package to select Helm charts that match a particular version spec, using `SimpleSpec`.

One of the Helm charts I am targeting generates versions for each commit of the form:

```
X.Y.Z-dev.0.<branch name>.<number of commits since X.Y.Z>
```

where X.Y.Z will be the next stable version, e.g. `0.1.0-dev.0.notmain.22`, `0.1.0-dev.0.main.21`, `0.1.0-dev.0.main.16`.

I want to be able to select all the versions from the `main` branch. In Helm, I can do this using the following constraint:

```
>=0.0.0-dev.0.main.0,<0.0.0-dev.0.main.999999999
```

The documentation seems to suggest that I should be able to use a similar constraint with `SimpleSpec`, however when I try this I get an empty list:

```
versions = ["0.1.0-dev.0.notmain.22", "0.1.0-dev.0.main.21", "0.1.0-dev.0.main.16", "0.1.0-dev.0.aardvark.23"]
version_range = semantic_version.SimpleSpec(">=0.0.0-dev.0.main.0,<0.0.0-dev.0.main.999")
print([v for v in versions if semantic_version.Version(v) in version_range])
```

Also, if I use `>=0.0.0`, I get all the versions, which is also not the expected behaviour. However this is covered by #42, and I consider it to be a bug by the SemVer spec.

**Comment by rbarrois** [comment]
Indeed, this should work; it's either a bug, or a documentation issue.

I'll look into it ;)

**Comment by rbarrois** [comment]
Actually, this seems to work as expected?

```python
>>> versions = [Version('0.1.0-dev.0.notmain.22'),  Version('0.1.0-dev.0.main.21'),  Version('0.1.0-dev.0.main.16'),  Version('0.1.0-dev.0.aardvark.23')]
>>> list(SimpleSpec(">=0.1.0-dev.0.main.0").filter(versions))
[Version('0.1.0-dev.0.notmain.22'),
 Version('0.1.0-dev.0.main.21'),
 Version('0.1.0-dev.0.main.16')]
>>> list(SimpleSpec("<0.1.0-dev.0.main.999").filter(versions))
[Version('0.1.0-dev.0.main.21'),
 Version('0.1.0-dev.0.main.16'),
 Version('0.1.0-dev.0.aardvark.23')]
>>> [v for v in versions if v in SimpleSpec(">=0.1.0-dev.0.main.0,<0.1.0-dev.0.main.999")]
[Version('0.1.0-dev.0.main.21'), Version('0.1.0-dev.0.main.16')]
```

In your code snippet, you have listed `0.0.0-dev` whereas your versions have `0.1.0-dev` in them :)
