### ISSUE TITLE
Check if two specs overlap/intersect

### ISSUE THREAD

**Issue by kian99** [rbarrois/python-semanticversion#139]
Is there a way to check if two specs overlap?

I.e. `SimpleSpec("1")` and `SimpleSpec("1.5")` have portions where they overlap.

The corresponding clauses for both:
`AllOf(Range('<', Version('2.0.0')), Range('>=', Version('1.0.0')))`
and
`AllOf(Range('<', Version('1.6.0')), Range('>=', Version('1.5.0')))`

**Comment by rbarrois** [comment]
There is no native API enabling this.
It might be possible to write an `overlaps(a, b)` function working on `BaseSpec` or `Clause` objects; I'm not sure it would be easy however.

Would you have more details on the use-case for that feature?

As a side note, `Spec` objects aren't covered by the official `semver.org` semantics, so we're treading in uncharted territory…

**Comment by kian99** [comment]
Good to know, thanks for the information. It does seem like it wouldn't be easy.

For context, I was looking at making an API for querying support information (and using the spec to cover a range). So the idea was to ensure that two specs don't overlap otherwise the user has entered information incorrect (i.e. using it for input validation).

**Comment by rbarrois** [comment]
I see; maybe you could ask the user to input a single spec expression: `SimpleSpec(">=1,<2")`?

Since a spec can describe arbitrary narrow ranges, it's better to accept a single expression!
