### ISSUE TITLE
API for bumping versions

### ISSUE THREAD

**Issue by RickEyre** [rbarrois/python-semanticversion#16]
What would you think of something like:

```python
version.bump_major()
version.bump_minor()
version.bump_patch()
```

Each of these would reset any lower levels in the versioning 'hierarchy'. So running `version.bump_major()` on `1.0.0-prerelease+build` would result in `2.0.0`.

**Comment by RickEyre** [comment]
Also thinking of:

```python
version.bump('major|minor|patch')
```

**Comment by rbarrois** [comment]
Just merged, thanks for the idea and the implementation :)
