### ISSUE TITLE
semver spec violation for versions with build metadata

### ISSUE THREAD

**Issue by mwarren** [rbarrois/python-semanticversion#18]
According to [semver 2.0.0](http://semver.org/spec/v2.0.0.html), spec rule number 10, two versions that differ only in build metadata should have the same precedence. However, ```cmp``` of two such versions returns non-zero:

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from semantic_version import Version
>>> cmp(Version('1.0.0'), Version('1.0.0+build'))
-1
```

I almost started working on a fix and pull request, but it looks from [pydoc in the code](https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L284) that this might be intentional?

**Comment by Shir0kamii** [comment]
I think i would be better to fix it, should it have been intentional or not. What are your opinion @rbarrois ?

**Comment by mwarren** [comment]
Sorry, I linked to the wrong bit of code. Relevant code is in the [build_cmp](https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L292) function.

**Comment by rbarrois** [comment]
Well, that's an interesting problem.
The only goal of that feature was to state that versions *without* build metadata take precedence over versions *with* metadata.

After reading some issues on the main SemVer repo, a release might include build metadata; this means that my assumptions were broken here.

I have just updated the code relating to that suggestion; this brings many changes.

**Comment by Shir0kamii** [comment]
Thank you for taking care of this !

**Comment by rbarrois** [comment]
Going out in the upcoming release :)

Thanks everybody for the help!!
