### ISSUE TITLE
Version bump from prereleases not working as expected

### ISSUE THREAD

**Issue by MinchinWeb** [rbarrois/python-semanticversion#24]
I was expecting that a prerelease version, when bumped, would go up to the 'full' or release version without bumping the main version number if not needed.

Probably makes more sense if I give examples.

What I expected:

```
1.0.0-dev --[major]--> 1.0.0
1.0.1-dev --[major]--> 2.0.0
1.1.0-dev --[major]--> 2.0.0

1.0.0-dev --[minor]--> 1.0.0
1.0.1-dev --[minor]--> 1.1.0
1.1.0-dev --[minor]--> 1.1.0

1.0.0-dev --[patch]--> 1.0.0
1.0.1-dev --[patch]--> 1.0.1
1.1.0-dev --[patch]--> 1.1.0
```

What currently happens:
```
1.0.0-dev --[major]--> 2.0.0
1.0.1-dev --[major]--> 2.0.0
1.1.0-dev --[major]--> 2.0.0

1.0.0-dev --[minor]--> 1.1.0
1.0.1-dev --[minor]--> 1.1.0
1.1.0-dev --[minor]--> 1.2.0

1.0.0-dev --[patch]--> 1.0.1
1.0.1-dev --[patch]--> 1.0.2
1.1.0-dev --[patch]--> 1.1.1
```

If this a bug in the implementation, or have I missed something in the spec? Thanks!

**Comment by rbarrois** [comment]
Hi,

That's indeed a good suggestion.
Bumping is not documented in the SemVer spec though.

I'd like to merge your patch, however you have mixed in various changes.
Could you update your pull request to merge commits 37474accc and 6643a985d while removing the two following ones?

**Comment by MinchinWeb** [comment]
Okay, I split it into two pull requests. #27 just contains the version bumping code, #28 is just updating the copyright year in the copyright statements to include this year (2015). The hashes of the the commits have changed, but otherwise it's the same code.

**Comment by rbarrois** [comment]
@MinchinWeb Thanks! I've finally merged this :)

**Comment by MinchinWeb** [comment]
:+1:
