### ISSUE TITLE
Support npm/composer extensions?

### ISSUE THREAD

**Issue by skwashd** [rbarrois/python-semanticversion#30]
npm and composer support the use of tilde (`~`) and caret (`^`) in version requirements.  Would you accept a well written and tested patch that implements support for this in comparisons?

**Comment by rbarrois** [comment]
Hi,

This looks like an interesting feature indeed!

Just a note though: could you point me to a description of exactly what these extensions handle?
This will ease up the review :)

Thanks!

**Comment by skwashd** [comment]
@rbarrois here is the info:

* composer docs - https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators
* npm docs - https://nodesource.com/blog/semver-tilde-and-caret#caret-tilde-what-s-the-difference-

Let me know if you need more info.

**Comment by rbarrois** [comment]
@skwashd Thanks for all.

I'm trying to bring back some life into my various open-source projects, so this PR might have to wait a couple more days before I get some time to look into it, sorry :/

And please ping me if you haven't received any answer by next week!!

**Comment by pfifi-puppet** [comment]
@rbarrois no rush.  I have run into some issues when extending this to support the full extended syntax as supported by npm and composer.  

When #31 and #32 are used together things break.  I have time scheduled to work on this again on Friday.

**Comment by skwashd** [comment]
@rbarrois I've updated #31 and #32.

**Comment by rbarrois** [comment]
@skwashd I've just merged and fixed this, thanks again for the suggestion!
