### ISSUE TITLE
SubfieldBase will be removed in Django 1.10

### ISSUE THREAD

**Issue by drewbrew** [rbarrois/python-semanticversion#43]
Warnings upon launching a Django 1.9.5 project using `semantic_version`:

```
/<snipped>/.venv/lib/python3.5/site-packages/semantic_version/django_fields.py:38: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  str('SemVerField'), (BaseSemVerField, models.CharField), {})

/<snipped>/.venv/lib/python3.5/site-packages/semantic_version/django_fields.py:41: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class VersionField(SemVerField):

/<snipped>/.venv/lib/python3.5/site-packages/semantic_version/django_fields.py:64: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class SpecField(SemVerField):
```

It looks like the solution is to remove `__metaclass__` and manually define the to/from Python methods: https://stackoverflow.com/questions/35166085/how-to-deal-with-subfieldbase-has-been-deprecated-use-field-from-db-value-inst

**Comment by tony** [comment]
@rbarrois due to this, python-semanticversion is currently broke for the stable release of django

**Comment by pghalliday** [comment]
Just got caught out by this and had to pin my Django version to <1.10 on a new project.
Will there be a release soon?

thanks for library btw :)

**Comment by rbarrois** [comment]
@pghalliday I plan to release this by the end of the week — too much work until then.

**Comment by pghalliday** [comment]
@rbarrois cool thanks

**Comment by rbarrois** [comment]
@pghalliday released ;)

**Comment by pghalliday** [comment]
awesome, thanks :)
