### ISSUE TITLE
Specs are separated using commas instead of spaces

### ISSUE THREAD

**Issue by BernhardPosselt** [rbarrois/python-semanticversion#46]
We are currently writing an API for which will be accessed with PHP and/or JS. Both have a semver package that supports ranges, however they split the ranges using spaces rather than spaces, e.g.

```
>=1.2.3 <2.0.0
```

and not

```
>=1.2.3,<2.0.0
```

AFAIK ranges are not part of semver, but it would be awesome to be compatible. 

There are two ways I can think of fixing this:
- Simply replace the comma with a space which would be backwards incompatible but cleaner, or
- When instantiating a Spec we check if the string contains a comma and save it in a bool attribute. When parsing the version and serializing back to a string we would inspect the flag and use a comma or space. This approach would be backwards compatible but not as nice :)

I could create a PR if you want, it seems these are the only lines that have to be adjusted:
- https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L503
- https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L532

What do you think?

Related:
- https://docs.npmjs.com/misc/semver
- https://packagist.org/packages/vierbergenlars/php-semver

**Comment by rbarrois** [comment]
Hey,

Thanks for the suggestion! A bit late, but this is now supported through `NpmSpec`:

```python
>>> semantic_version.Version("3.0.2") in semantic_version.NpmSpec(">=3.0.0 <3.0.7")
True
```
