### ISSUE TITLE
Semver 3.0 Compatibility?

### ISSUE THREAD

**Issue by westurner** [rbarrois/python-semanticversion#47]
Is python-semanticversion compatible with Semver 3.0?
- Semver 3.0:
  - | Standard: http://docs.openstack.org/developer/pbr/semver.html
  - | Src: https://github.com/openstack-dev/pbr/blob/master/doc/source/semver.rst

This adds an #examples section (of potential test cases):
- https://github.com/openstack-dev/pbr/pull/14

**Comment by rbarrois** [comment]
It is only compatible with semver 2.0; what would be the benefits of semver 3.0 for this?

**Comment by westurner** [comment]
```
Changes vs SemVer 2.0

1. dev versions are defined. These are extremely useful when dealing with
CI and CD systems when ‘every commit is a release’ is not feasible.
2. All versions have been made PEP-440 compatible, because of our deep
roots in Python. Pre-release versions are now separated by . not -, and use
a/b/c rather than alpha/beta etc.
```

- Compatibility with semver 3 dev and PEP440 versions
  - OpenStack

**Comment by rbarrois** [comment]
I'm going to close this for now, as "Linux/Python Compatible Semantic Versioning" (`LPCSV` below) is not an evolution of SemVer, but a different and incompatible standard.

Indeed:
* Pre-release versions from SemVer aren't valid "LPCSV" versions;
* "LPCSV" pre-release versions aren't valid SemVer versions;
* "LPCSV" doesn't seem to have been proposed as an upgrade to SemVer.

Building support for that scheme wouldn't be compatible with the current scheme, and should rather be built as a separate package (which might opt to rely on this package's internals though).
