### ISSUE TITLE
Construct Version objects from tuples

### ISSUE THREAD

**Issue by drdavella** [rbarrois/python-semanticversion#53]
It would be useful to be able to do the following:
```python
import semantic_version as sv
version = sv.Version((1,0,0))
```
I would be willing to take on a PR for this feature myself, if it seems reasonable.

**Comment by Julian** [comment]
-1 for tuples personally, but +1 on the idea that there should be a non-string way of constructing `Version`s (IMHO it should e.g. take a `major`, `minor`, and `patch` argument and deprecate the str argument)

It's definitely awkward to construct `Version` objects now as it looks like the [codebase itself](https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L95) seems to corroborate when it tries to construct new versions out of old ones.

**Comment by rbarrois** [comment]
Thanks for the suggestion!
I've added this to version 2.7.0:
```python
>>> semantic_version.Version(major=3, minor=2, patch=4)
Version('3.2.4')
```
