### ISSUE TITLE
Version.__repr__ does not respect subclasses

### ISSUE THREAD

**Issue by kgbaird** [rbarrois/python-semanticversion#55]
The current `__repr__` implementation hard codes `Version` as the class name. This means any subclasses will be represented with `Version` instead of their class name. Would it be feasible to change this so the class name was shown instead of the hard coded `Version`.

I'm willing to work on this, and in fact, already have a commit staged up in a fork, if this change is acceptable.

**Comment by rbarrois** [comment]
Thanks for the features! I've merged the PR ;)
