### ISSUE TITLE
Version comparison bug

### ISSUE THREAD

**Issue by ghost** [rbarrois/python-semanticversion#60]
Hi, 

I created an arbitrary version and have found bug. None of these come to true. I would assume that `a>b` has an outcome as `True`

`import semantic_version`
`a = semantic_version.Version.coerce('0.1.2.3.4.3-beta4.5.6.7-alpha')`
`b = semantic_version.Version('0.1.2')`
`print(a > b) # False`
`print(a < b) # False` 
`print(a ==b) # False`

**Comment by rbarrois** [comment]
This is totally normal behaviour :)

```python
>>> import semantic_version
>>> semantic_version.Version.coerce('0.1.2.3.4.3-beta4.5.6.7-alpha')
Version('0.1.2+3.4.3-beta4.5.6.7-alpha')
>>> semantic_version.Version('0.1.2')
Version('0.1.2')
```

The first version is coerced to a ``build``-variant of ``0.1.2``. According to SemVer, the build part must be ignored when comparing versions.
Thus, two versions with the same ``major.minor.patch`` parts and a different build identifier cannot be compared: they are not equal, but none is greater than the other.

In other words, there is no total ordering among versions with a "build" part.
