### ISSUE TITLE
.x versioning is not supported

### ISSUE THREAD

**Issue by r-bit-rry** [rbarrois/python-semanticversion#66]
According to NPM semver documentation .x behaviour is supposed to act like:

    Patch releases: 1.0 or 1.0.x or ~1.0.4
    Minor releases: 1 or 1.x or ^1.0.4
    Major releases: * or x

However Spec class doesn't parse versions with 'x' instead of a digit

**Comment by rbarrois** [comment]
The semver.org documentation doesn't define how to declare "version specification", which are defined differently by pip, NPM, Debian, etc.

The library tries to implement a reasonable subset of those, thus the absence of support for NPM specific rules.

Would you be interested in helping on that topic, i.e designing a clean API to define various flavours of "version range specifications"?

**Comment by r-bit-rry** [comment]
Yeah I can look into that.

**Comment by arashd** [comment]
+1 for this. Would love to see .x support.

**Comment by rbarrois** [comment]
It's now included!
```python
>>> semantic_version.Version("3.2.3") in semantic_version.NpmSpec("=3.2.x")
True
```
