### ISSUE TITLE
next_patch 

### ISSUE THREAD

**Issue by vabic** [rbarrois/python-semanticversion#67]
>>> v1 = semantic_version.Version('1.1.1-pre+build')
>>> v2 = v1.next_patch()
>>> str(v2)
'1.1.1'

**Comment by guboi72** [comment]
Vs the readme
`>>> v = semantic_version.Version('1.1.1-pre+build')
>>> new_v = v.next_patch()
>>> str(new_v)
'1.1.2'`

**Comment by rbarrois** [comment]
Oh, that's a good catch, although the tests are testing for the first version.

I'm unsure about what someone would expect here: should the ``next_patch()`` / ``next_minor()`` / ``next_major()`` of a pre-release be that release, or the next release?
