### ISSUE TITLE
Support for advanced range separator: pipe

### ISSUE THREAD

**Issue by ulziibay** [rbarrois/python-semanticversion#70]
Per https://docs.npmjs.com/misc/semver#advanced-range-syntax, using `||` as logical-or for ranges is allowed.
Requesting to add `Spec()` be aware of such initializers.

On: `semantic-version==2.6.0` and `python==3.6`, 
`Spec("1.0.0 || <=0.9.4")` throws with:
```
ValueError: Invalid version string: '1.0.0 || <=0.9.4'
```

**Comment by rbarrois** [comment]
This is now available (since version 2.7.0) through `NpmSpec`:

```python
>>> import semantic_version
>>> semantic_version.Version("3.0.0") in semantic_version.NpmSpec("<2.4.0 || >=3.0.0")
True
```
