### ISSUE TITLE
Spec(`~=1.1.0`) matches Version(`1.2.0-foobar`)

### ISSUE THREAD

**Issue by nathandines** [rbarrois/python-semanticversion#72]
I would expect this to return `False`, but when comparing the versions mentioned in the title, I'm getting a `True` result. Is my interpretation of the rules incorrect, or is this a bug?

Example:
```py
>>> semantic_version.match('~=1.1.0', '1.2.0-foobar')
True
```

**Comment by rbarrois** [comment]
It's a bug, but should be now fixed in master — sorry for the long delay!
