### ISSUE TITLE
Version 2.7 broke compatibility

### ISSUE THREAD

**Issue by tzoiker** [rbarrois/python-semanticversion#79]
Ironically, semver library does not follow semver. For example, removing `specs` property from `Spec` broke compatibility with version 2.6. Please, introduce breaking changes with major bump only.

**Comment by rbarrois** [comment]
Damn, this is an oversight on my side :/
It's still available through `iter(Spec)`, but I'll push an update later today to fix it.

Thanks for the report!

**Comment by rbarrois** [comment]
(this also means that no test checked that the attribute existed, I think :wink:)

**Comment by rbarrois** [comment]
Fixed in release 2.8.1 ;)
