### ISSUE TITLE
Possibly another breaking change between 2.6.0 and 2.7.0 (not fixed in 2.8.1)

### ISSUE THREAD

**Issue by elemental-lf** [rbarrois/python-semanticversion#80]
I'm currently investigating a problem in an application of mime which works fine with 2.6.0 and breaks with 2.7.0 and later versions including 2.8.1.
The exception I get is (with 2.8.1):
```
s1:4: DeprecationWarning: Partial versions will be removed in 3.0; use SimpleSpec('1.x.x') instead.
  version_obj = semantic_version.Version(version, partial=True)
Traceback (most recent call last):
  File "s1", line 5, in <module>
    if version_obj not in supported:
  File "venv/lib64/python3.7/site-packages/semantic_version/base.py", line 642, in __contains__
    return self.match(version)
  File "venv/lib64/python3.7/site-packages/semantic_version/base.py", line 630, in match
    return self.clause.match(version)
  File "venv/lib64/python3.7/site-packages/semantic_version/base.py", line 745, in match
    return all(clause.match(version) for clause in self.clauses)
  File "venv/lib64/python3.7/site-packages/semantic_version/base.py", line 745, in <genexpr>
    return all(clause.match(version) for clause in self.clauses)
  File "venv/lib64/python3.7/site-packages/semantic_version/base.py", line 910, in match
    return version >= self.target
  File "venv/lib64/python3.7/site-packages/semantic_version/base.py", line 467, in __ge__
    return self.precedence_key >= other.precedence_key
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
Here is a code snippet to reproduce the issue:
```python
import semantic_version
supported=semantic_version.Spec('>=1,<2')
version = '1'
version_obj = semantic_version.Version(version, partial=True)
if version_obj not in supported:
  raise RuntimeError('Configuration has unsupported version of "{}".'.format(version))
```
It obviously has something to do with the partial version specification and it's possible that I'm not using `semantic-version` correctly.

**Comment by rbarrois** [comment]
Partial versions were only intended as part of the `Spec` side of things; a `Spec` should only match a non-partial `Version`.
It might have worked, but that wasn't expected.

Have you tried using `Version.coerce('1') in Spec('>=1,<2')`?

**Comment by elemental-lf** [comment]
Thanks for fast reply. I've adapted my code to use `coerce` and now everything is working again with 2.8.1. But I still think this is a breaking change as the public interface in 2.6.0 is:
```python
class Version(object):
[...]
    def __init__(self, version_string, partial=False):
        major, minor, patch, prerelease, build = self.parse(version_string, partial)
[...]
```
So `partial` is a valid public parameter for the constructor and it's handled by `parse` accordingly. So intentions are not really relevant I think, the public interface and the behaviour of the code is. And I just found that this usage was even documented in the old `README.rst`:
```text
In order to define "relaxed" version strings, you must pass in partial=True:
>>> v = semantic_version.Version('0.1', partial=True)
>>> list(v)
[0, 1, None, None, None]
```

**Comment by rbarrois** [comment]
The usage of partial versions was documented, and is still supported!
It's only the `Spec` class that wasn't designed to work with a partial version, nor documented as such ;)

**Comment by elemental-lf** [comment]
Thanks for the clarification. As I've adapted my code and nobody else complained about this particular issue yet I'm going to close it.
