### ISSUE TITLE
Incorrect matching when using `partial` keyword argument in `Version`

### ISSUE THREAD

**Issue by jasongraham** [rbarrois/python-semanticversion#81]
Python versions: 3.7.4 and 3.6.9
OS: Windows 10

I've found interesting behavior in version 2.8.1 which I believe is a bug.

```python
>>> # Expected, good
>>> Version("1.0.0") in Spec("==1.0.0")
True
>>> Version("1.0.0") in Spec("!=1.0.0")
False

>>> # Unexpected, probably a bug
>>> # Expected that these would match above without partial
>>> Version("1.0.0", partial=True) in Spec("==1.0.0")
True
>>> Version("1.0.0", partial=True) in Spec("!=1.0.0")
True

>>> # Unexpected, probably a bug
>>> # Expected that these would match above without partial
>>> Version("1", partial=True) in Spec("==1.0.0")
False
>>> Version("1", partial=True) in Spec("!=1.0.0")
True
```

In version 2.6.0, the `partial` keyword argument seemed to add missing minor / patch numbers as `0`.  It seems to be doing something different now.

```python
>>> Version("1.0.0") == Version("1.0.0", partial=True)
True
>>> Version("1.0.0") != Version("1.0.0", partial=True)
True
>>> Version("1.0.0") == Version("1", partial=True)
False
```

**Comment by jasongraham** [comment]
I believe that this is similar to #80, which I had somehow missed prior to creating this issue.

Reading through #80, you are saying that `Spec`s were not intended to be used on partial `Version`s?

What about comparing partial and non-partial versions?

**Comment by rbarrois** [comment]
Hi! Indeed, `Version(partial=True)` is a special object, mostly an implementation detail of `Spec`, but exposed in the docs.

How do you use those partial versions? Which concept do you use them for?

**Comment by rbarrois** [comment]
Thanks for the information! I should have made that part more prominent in the changelog I guess...

Since `.coerce()` works for you, I'll close the issue for now — but feel free to reopen it needed :smiley:
