### ISSUE TITLE
NpmSpec doesn't properly handle prerelease versions

### ISSUE THREAD

**Issue by nwalters512** [rbarrois/python-semanticversion#86]
Consider the npm version range `>0.0.0-alpha <0.0.0-beta`. I would expect the version `0.0.0-alpha.0` to match this version range, and evaluating the constraints independently tells me this should be true:

```python
>>> from semantic_version import Version
>>> Version('0.0.0-alpha.0') > Version('0.0.0-alpha')
True
>>> Version('0.0.0-alpha.0') < Version('0.0.0-beta')
True
```

However, `NpmSpec` reports that this is not the case:

```python
>>> from semantic_version import Version, NpmSpec
>>> Version('0.0.0-alpha.0') in NpmSpec('>0.0.0-alpha <0.0.0-beta')
False
```

This appears to be a bug, but it's possible that my understanding of prerelease versions in compound npm version ranges is off.

Thanks for all the work on this library!

**Comment by rbarrois** [comment]
Hi!

Thanks for the bug report, well spotted!

A bugfix release is on its way ;)

**Comment by nwalters512** [comment]
Thanks for the quick fix!
