### ISSUE TITLE
Can `Version.coerce()` accept leading zeroes?

### ISSUE THREAD

**Issue by andrew-ni** [rbarrois/python-semanticversion#89]
Is it possible to allow something like this? `Version.coerce('1.01.1')` 

This raises a ValueError: Invalid leading zero in minor: '1.01.1'

but is there a specific reason why the coerce function shouldn't be able to handle this? This would be very useful as a lot of programs (docker, ubuntu) use the format: `YY.MM.patch`

**Comment by rbarrois** [comment]
Hey, thanks for the report; this does look like a neat enhancement indeed :)

**Comment by rbarrois** [comment]
And that's fixed, released in 2.8.4 :)
