### ISSUE TITLE
A version matching wildstar patch SimpleSpec is not matched by a version with the same prefix

### ISSUE THREAD

**Issue by numaru** [rbarrois/python-semanticversion#98]
### Description

It is specified in [PEP440](https://www.python.org/dev/peps/pep-0440/#version-matching) that the version `1.1.8` should match the spec `==1.1.*`. The `SimpleSpec` does not fulfill this requirement.  

### Reproduction snippet

```python
from semantic_version import Version, SimpleSpec

version = Version("1.1.8")
assert version not in SimpleSpec("==1.1") # Not equal, so 1.1.8 does not match clause
assert version in SimpleSpec("==1.1.8") # Equal, so 1.1.8 matches clause
assert version in SimpleSpec("==1.*.*") # Same prefix, so 1.1.8 matches clause and it works
assert version in SimpleSpec("==1.1.*") # Same prefix, so 1.1.8 matches clause but it fails
```

### Environment
python: 3.8.0
semantic-version: 2.8.4

**Comment by rbarrois** [comment]
Thanks for the report!

It seems that wildcards are supported in the code, but neither documented nor tested...
I'll take a look into that.

Also, please note that `SimpleSpec` does not intend to replicate PEP440; for that, we should instead create a `PySpec` (or `PEP440Spec` or `PyPASpec`) :wink:

**Comment by rbarrois** [comment]
And it's live in version `2.8.5` ;)
